# Day 2: Creating and Manipulating Arrays

## Q1

In [1]:
import numpy as np

In [2]:
# Check version of `NumPy` installed
!python -m pip list | grep numpy


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


## Q2

In [3]:
list1 = [2, 3, 4, 6]

In [4]:
arr = np.array(list1)
arr

array([2, 3, 4, 6])

In [5]:
arr.shape

(4,)

In [6]:
arr.size

4

In [7]:
arr_reversed = arr[::-1]
arr_reversed

array([6, 4, 3, 2])

## Q3

In [8]:
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]

In [9]:
arr = np.array((list1, list2))
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [10]:
arr.shape

(2, 4)

In [11]:
arr.ndim

2

In [12]:
arr.dtype

dtype('int64')

## Q4

In [13]:
list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]

In [14]:
arr = np.array((list1, list2, list3), dtype="int64")
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [15]:
arr.dtype

dtype('int64')

## Q5

In [16]:
arr = np.array((list1, list2, list3), dtype="float")
arr

array([[ 2. ,  3. ,  4. ,  6. ],
       [ 8. , 10.1, 12. , 14. ],
       [16. , 18. , 20. , 22.1]])

In [17]:
# It isn't possible to create an array of both floats and integers, since an array must have homogeneous data types.
arr.dtype

dtype('float64')