# Day 2: Creating and Manipulating Arrays

## Q1

In [1]:
import numpy as np

In [2]:
# Check `NumPy` version
np.version.version

'1.26.4'

## Q2

In [3]:
list1 = [2, 3, 4, 6]

In [4]:
# Create a 1D array from the list
arr = np.array(list1)
arr

array([2, 3, 4, 6])

In [5]:
# Check the shape of the array
arr.shape

(4,)

In [6]:
# Check the size of the array
arr.size

4

In [7]:
# Write a function to reverse the array
def reverse(arr):
    return arr[::-1]

reverse(arr)

array([6, 4, 3, 2])

## Q3

In [8]:
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]

In [9]:
# Create an array from the two lists
arr = np.array((list1, list2))
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [10]:
# Check the shape of the array
arr.shape

(2, 4)

In [11]:
# Check the dimensions of the array
arr.ndim

2

In [12]:
# Check the data type of the array
arr.dtype

dtype('int64')

## Q4

In [13]:
list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]

In [14]:
# Create an array from the lists with an `int64` data type
arr = np.array((list1, list2, list3), dtype="int64")
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [15]:
arr.dtype

dtype('int64')

## Q5

In [16]:
arr = np.array((list1, list2, list3), dtype="float")
arr

array([[ 2. ,  3. ,  4. ,  6. ],
       [ 8. , 10.1, 12. , 14. ],
       [16. , 18. , 20. , 22.1]])

In [17]:
# It isn't possible to create an array of both floats and integers, since an array must have homogeneous data types.
arr.dtype

dtype('float64')