# Day 6: Array Manipulation and Vector Operations

In [1]:
import numpy as np

In [2]:
list_str = ["23", "12", "90", "28", "30"]

## Q1

In [3]:
# Create an array with the list above, casting strings to integers
arr1 = np.array(list_str, dtype=int)
arr1

array([23, 12, 90, 28, 30])

In [4]:
# Calculate standard deviation
np.std(arr1)

27.419700946582186

## Q2

In [5]:
# Cast values to floats
arr2 = arr1.astype(float)
arr2

array([23., 12., 90., 28., 30.])

## Q3

In [6]:
# Calculate sum of some of the values
np.sum(arr2[2:])

148.0

## Q4

In [7]:
# Create 2D array of random integers
rng = np.random.default_rng(seed=7)
arr3 = rng.integers(0, 101, (5, 5))
arr3

array([[95, 63, 69, 90, 58],
       [78, 84, 22,  5, 30],
       [28, 88, 92,  0, 50],
       [82, 13, 80, 12, 47],
       [82, 30, 34, 28, 72]])

In [8]:
# Find minimum
np.min(arr3)

0

In [9]:
# Find maximum
np.max(arr3)

95

In [10]:
# Find mean
np.mean(arr3)

53.28

In [11]:
# Find standard deviation
np.std(arr3)

30.12310740942906

## Q5

In [12]:
first_names = ["John", "Kenny"]
last_names = ["Smith", "Sakula"]

In [13]:
# Create array to store first names and last names
names = np.array((first_names, last_names))
names

array([['John', 'Kenny'],
       ['Smith', 'Sakula']], dtype='<U6')

In [14]:
# Create arrays joining first names with last names
name1 = np.char.join("", names[:, 0]).astype("U6")
name1

array(['John', 'Smith'], dtype='<U6')

In [15]:
name2 = np.char.join("", names[:, 1]).astype("U6")
name2

array(['Kenny', 'Sakula'], dtype='<U6')