# Day 5: Array Creation and Vector Operations

In [1]:
import numpy as np

In [2]:
list_numbers = [[12, 23, -45], [18, -77, -44]]

## Q1

In [3]:
# Create an array from the list
arr1 = np.array(list_numbers)
arr1

array([[ 12,  23, -45],
       [ 18, -77, -44]])

In [4]:
# Return all negative numbers in the array
arr1[arr1 < 0]

array([-45, -77, -44])

## Q2

In [5]:
# Multiply each element by 2
arr2 = arr1 * 2
arr2

array([[  24,   46,  -90],
       [  36, -154,  -88]])

## Q3

In [6]:
# Calculate sum of numbers on axis 1
arr2.sum(1)

array([ -20, -206])

## Q4

In [7]:
# Calculate sum of numbers on axis 0
arr2.sum(0)

array([  60, -108, -178])

## Q5

In [8]:
# Create an array of numbers from 0 to 99
arr3 = np.arange(100).reshape(2, 5, 10)
arr3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

## Q6

In [9]:
# Slice the row [50, ..., 59] from the array above
arr3[1, 0]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

## Q7

In [10]:
arr1

array([[ 12,  23, -45],
       [ 18, -77, -44]])

In [11]:
# Identify numbers in row 1 that are greater than those in row 2
row1_greater_than_row2 = arr1[0] > arr1[1]
row1_greater_than_row2

array([False,  True, False])

In [12]:
# Count how many numbers fit the condition above
arr1[0][row1_greater_than_row2].size

1

In [13]:
# Alternative solution
np.greater(arr1[0], arr1[1]).sum()

1